services:
  - type: web
    name: meetx-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: MONGO_URI
        value: your_mongo_connection_string
      - key: JWT_SECRET
        value: your_secret_key
      - key: PORT
        value: 10000
